name: Periodic Commit

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  commit-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Make a change
        run: |
          # Make your changes here. For example, modifying a file
          echo "$(date) Hello. Not everyone works by committing code to public repositories all the time" > messages.txt
      
      - name: Configure Git
        run: |
          git config --global user.name '${{ secrets.NAME }}
          git config --global user.email '${{ secrets.EMAIL }}'
      
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git add .
          git commit -m "Periodic update: $(date)"
          git push

