name: Periodic Commit

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  
permissions: write-all
jobs:

  commit-change:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4 
      
      - name: Make a change
        run: |
          echo "$(date) Hello. Not everyone works by committing code to public repositories all the time" > messages.txt

      - name: Commit changes
        run: |
          git add messages.txt
          git commit -m "Update $(date): Running"
      
      - name: Push changes
        run: |
          git push origin main
