name: Periodic Commit

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  commit-change:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4 
      
      - name: Make a change
        run: |
          echo "$(date) Hello. Not everyone works by committing code to public repositories all the time" > messages.txt
      
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
